dist: trusty
sudo: required
language:
  - generic
cache:
  - apt
services:
  - docker

env:
  - DISTR=indigo BASEIMG=osrf/ros:indigo-desktop-full
  - DISTR=kinetic BASEIMG=ros:kinetic

before_script:
  - docker pull ${BASEIMG}

script:
  - docker build -f Dockerfile.${DISTR} --tag ros:aero_${DISTR} .
